name: Build and test Docker multiplatform images
on:
  push:
    branches:
      - '**'
      - '!master'
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['10.16', '12.22', '14.13', '14.15', '16.17']
        platform: ['linux/amd64', 'linux/arm64']
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ matrix.image }}"
          platforms: "${{ matrix.platform }}"
          load: true
          tags: somosyampi/docker-nodejs:${{ matrix.image }}-test
      -
        name: Test image
        run: |
          docker image inspect somosyampi/docker-nodejs:${{ matrix.image }}-test
          docker run --rm somosyampi/docker-nodejs:${{ matrix.image }}-test node --version
          docker run --rm somosyampi/docker-nodejs:${{ matrix.image }}-test npm --version
          docker run --rm somosyampi/docker-nodejs:${{ matrix.image }}-test yarn --version
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: somosyampi/docker-nodejs:${{ matrix.image }}-test
          annotations: true
          dockerfile: ./${{ matrix.image }}/Dockerfile
